console.log(Math.min(0, 150, 30, 20, -8))
console.log(Math.max(0, 150, 30, 20, -8))
console.log(Math.random() != Math.random())
console.log(Math.round(4.7))
console.log(Math.round(4.3))
console.log(Math.ceil(4.3))
console.log(Math.floor(4.7))
console.log(Math.abs(-4.7))
console.log(Math.abs(4.7))
console.log(Math.cos(0.0))
console.log(Math.acos(0.0))
console.log(Math.asin(0.0))
console.log(Math.sin(0.0))
console.log(Math.atan(0.0))
console.log(Math.tan(0.0))
console.log(Math.exp(0.0))
console.log(Math.log(1.0))
console.log(Math.pow(2.0, 2.0))
console.log(Math.sqrt(4.0))
